//generated by fenrisulfr
package bleach.module.message
{
	public final class ProtocolType
	{
		public static const CM_HeartBeat:int = 1;
		public static const SM_HeartBeat:int = 2;
		public static const SM_Error:int = 3;
		public static const CM_CheckAccount:int = 101;
		public static const SM_CheckAccount:int = 102;
		public static const CM_CreatePlayer:int = 103;
		public static const SM_CreatePlayer:int = 104;
		public static const CM_Login:int = 105;
		public static const SM_Login:int = 106;
		public static const CM_EnterGameCenter:int = 107;
		public static const SM_EnterGameCenter:int = 108;
		public static const CM_GetRoomList:int = 109;
		public static const SM_GetRoomList:int = 110;
		public static const CM_CreateRoom:int = 111;
		public static const SM_CreateRoom:int = 112;
		public static const CM_SelectSection:int = 113;
		public static const SM_SelectSection:int = 114;
		public static const CM_EnterRoom:int = 115;
		public static const SM_EnterRoom:int = 116;
		public static const SM_UpdateRoom:int = 117;
		public static const CM_ExitRoom:int = 118;
		public static const SM_ExitRoom:int = 119;
		public static const CM_Ready:int = 120;
		public static const SM_Ready:int = 121;
		public static const CM_UpdateSlot:int = 122;
		public static const SM_UpdateSlot:int = 123;
		public static const CM_BeginBattle:int = 124;
		public static const SM_BeginBattle:int = 125;
		
	}
}